### ISSUE TITLE
The global option collectionPreRequestScripts is not working

### ISSUE THREAD

**Issue by samuelmendezfx** [apideck-libraries/portman#148]
The global option `collectionPreRequestScripts` is not working, but `valueReplacements` does. 
Nothing appears on the Pre-request Script tab, for any test.

```
"globals": {
    "collectionPreRequestScripts": [
      "pm.request.headers.upsert({key: 'accept', value: 'application/json'})"
    ],
    "keyValueReplacements": {},
    "valueReplacements": {
      "<Bearer Token>": "{{bearerToken}}"
    },
    "rawReplacements": []
  }
```

As you can see, I want to modify the `Accept` header. I also tried with the option `overwriteRequestHeaders` but it didn't work.

Any help?

**Comment by samuelmendezfx** [comment]
I don't know how or when but it started working

**Comment by thim81** [comment]
@samuelmendezfx Nice to hear that problems solve themselves, that are the best kind.

As a side note, the `overwriteRequestHeaders` is a bit cleaner to use, instead of the `collectionPreRequestScripts ` since it means that generated Postman is in a final state, while the pre-request script happens in Postman on every request.
The `overwriteRequestHeaders` should work, if you have targeted the overwrite properly. If it wouldn't work, feel free to report a issue.
