### ISSUE TITLE
Variation test generation - target openAPI response

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/portman#154]
Currently you can specify various types of target for which contract/content/... test type will be applied.

It would be interesting to define the expected OpenAPI response (which code) and the attached response content, in a structured manner. In case OpenAPI response is not defined, no requests should be generated in the variation folder.

**Comment by schelv** [comment]
Maybe it is possible to generate the variation tests without specifying the specific http status response code.

One option would be to expect some form of 4xx response code, since the input data is incorrect.

The other option would be to accept/tolerate any response code as long as it's not a successful (2xx) or server error (5xx).

For both options I think it's a good idea to check if the (4xx?) response code given by the server is listed in the spec.

**Comment by thim81** [comment]
Closing this new feature request, since the feature is included in the 1.10.0 release.

By adding the "openApiResponse" config to the "variationTests" section, the OpenAPI response object code/name defined will be used for the created variation. If the response code entered would not exist in the OpenAPI definition, no variation will be generated. If the "openApiResponse" config not is defined, the 1st response object from OpenAPI will be taken as expected response.
