### ISSUE TITLE
Multiple assertions as part of a single test

### ISSUE THREAD

**Issue by schelv** [apideck-libraries/portman#235]
I've been using portman to generate tests in a gitlab ci pipeline and it works great =)
Thanks for the effort that has been put into this project.

There is one tiny thing that can be improved.
I noticed that the number of tests does not match the number of api calls being made.
![image](https://user-images.githubusercontent.com/13403863/148943753-8b66ec6d-7267-44dc-9dd1-b8fc4229d6be.png)

This is probably because there are several tests generated for one API call.
Having [one test with multiple assertions](https://learning.postman.com/docs/writing-scripts/script-references/test-examples/#using-multiple-assertions) for each api call could make the test results more clear.

Could this be an option when generating the tests?

**Comment by thim81** [comment]
@schelv Portman generates for 1 test = 1 assertion

This is done on purpose, so that the results are also very clear and verbose what failed or succeeded.

```json
// Validate status 2xx 
pm.test("[GET]::/portal/v1/tenants/:tenantId/accounts - Status code is 2xx", function () {
   pm.response.to.be.success;
});
// Validate if response header has matching content-type
pm.test("[GET]::/portal/v1/tenants/:tenantId/accounts - Content-Type is application/json", function () {
   pm.expect(pm.response.headers.get("Content-Type")).to.include("application/json");
});
// Validate if response has JSON Body 
pm.test("[GET]::/portal/v1/tenants/:tenantId/accounts - Response has JSON Body", function () {
    pm.response.to.have.jsonBody();
});
// Validate if response matches JSON schema 
pm.test("[GET]::/portal/v1/tenants/:tenantId/accounts - Schema is valid", function() {
    pm.response.to.have.jsonSchema(schema,{unknownFormats: ["int32", "int64"]});
});
```

Results in Postman:
![2022-01-11 at 15 19 21](https://user-images.githubusercontent.com/952446/148959735-13240c19-80da-4664-8464-5a7e3b7dd4a8.png)

If we would group all the assertions under 1 test, it would be very difficult to see in Postman which assertion failed and which succeeded. Another downside of grouping the assertions is that, the test will fail and only output the first failed assertion, if there are multiple, which makes it less handy to figure what is wrong.

```json
pm.test("[GET]::/portal/v1/tenants/:tenantId/accounts - Valid API response", function () {
   pm.response.to.be.success;
   pm.expect(pm.response.headers.get("Content-Type")).to.include("application/json");
   pm.response.to.have.jsonSchema(schema,{unknownFormats: ["int32", "int64"]});
});
```

Success show only the test
![2022-01-11 at 15 24 49](https://user-images.githubusercontent.com/952446/148960739-08628303-0daf-423e-9c1d-f8e3a6743ef8.png)


Failure shows which 1st failed assertion
![2022-01-11 at 15 24 08](https://user-images.githubusercontent.com/952446/148960627-a0acdd19-b7eb-4626-bac1-2f73740ac255.png)

**Comment by schelv** [comment]
That makes sense!
Thank you for the explanation
