### ISSUE TITLE
Allow specifying tests on Collection level

### ISSUE THREAD

**Issue by wedi** [apideck-libraries/portman#305]
I tried to setup a global test for a postman collection but failed. Does this work somehow?

If so, this is a polite nudge to clarify the - quite difficult to read - documentation in this regard.
If no, this is a polite question if you could make this possible.

Thank you.

**Comment by thim81** [comment]
@wedi Could you elaborate what you mean with a "global" test?

**Comment by savage-alex** [comment]
Perhaps you mean tests for every operation in the API? If so we have shared our "base config" that will apply to the whole definition here https://github.com/apideck-libraries/portman/discussions/301 if its of help

**Comment by wedi** [comment]
Exactly, I'd like to specify a test for every operation by populating the test script of the collection aka the "Tests" input when you click on the collection name in postman (see screenshot). So collection wide tests is probably a better term than global.

In the meantime I managed to do it similar to #301 by adding it to every operation.

I'd prefer the collection wide test because of two reasons. Firstly it looks cleaner to me if you apply the very same test to every operation. Secondly I'd like to add a kind of boilerplate test that you'd need to adapt for one off checks. That doesn't work if you would need to edit the test of every operation.

```json
{
  "tests": {
    "extendTests": [
      {
        "openApiOperation": "*::/*",
        "overwrite": true,
        "tests": [
          "console.log(pm.response); if (pm.response.code === 401) { pm.collectionVariables.set('bearerToken', ''); console.log('Authentication failed. `bearerToken` reset. Try again.'); }"
        ]
      }
    ]
  },
  "globals": {
    "collectionPreRequestScripts": ["file:portman/prerequest-script.js"],
    "securityOverwrites": {
      "bearer": {
        "token": "{{bearerToken}}"
      }
    }
  }
}
```

![Screenshot Postman 2022-04-04 09-24-06](https://user-images.githubusercontent.com/1466269/161494324-4f8b48f7-8df5-4b0e-adfd-a09cf3118922.png)

**Comment by wedi** [comment]
As a side note: You can tell from the config that I am abusing the tests to avoid authenticating for each and every operation. Can you think of a smarter way to do this?

**Comment by thim81** [comment]
> Exactly, I'd like to specify a test for every operation by populating the test script of the collection aka the "Tests" input when you click on the collection name in postman (see screenshot). So collection wide tests is probably a better term than global.
> 
> In the meantime I managed to do it similar to #301 by adding it to every operation.
> 
> I'd prefer the collection wide test because of two reasons. Firstly it looks cleaner to me if you apply the very same test to every operation. Secondly I'd like to add a kind of boilerplate test that you'd need to adapt for one off checks. That doesn't work if you would need to edit the test of every operation.
> 
> `collectionPreRequestScripts` in `globals` sets the collection wide pre request script so what I was looking for is a `collectionTests` key in `globals`.
> 
> ```json
> {
>   "tests": {
>     "extendTests": [
>       {
>         "openApiOperation": "*::/*",
>         "overwrite": true,
>         "tests": [
>           "console.log(pm.response); if (pm.response.code === 401) { pm.collectionVariables.set('bearerToken', ''); console.log('Authentication failed. `bearerToken` reset. Try again.'); }"
>         ]
>       }
>     ]
>   },
>   "globals": {
>     "collectionPreRequestScripts": ["file:portman/prerequest-script.js"],
>     "securityOverwrites": {
>       "bearer": {
>         "token": "{{bearerToken}}"
>       }
>     }
>   }
> }
> ```
> 
> ![Screenshot Postman 2022-04-04 09-24-06](https://user-images.githubusercontent.com/1466269/161494324-4f8b48f7-8df5-4b0e-adfd-a09cf3118922.png)

Portman does not yet support "collectionTestScripts", it would be a valid feature addition.
For now your approach of `extendTests` with targeting `"openApiOperation": "*::/*"` would inject the test in all requests.

**Comment by thim81** [comment]
> As a side note: You can tell from the config that I am abusing the tests to avoid authenticating for each and every operation. Can you think of a smarter way to do this?

It feels that you are testing a "variation".

In Portman we aim for "happy path" test automation (expect HTTP 2xx responses) and facilitate "unhappy path" tests (expect everything except a 2xx). 
To facilitate the unhappy path testing, Portman introduces "variations" & "fuzzing".

A "variation" means that you test a request for pretty much a variation of a default request, which can be a 2xx response or a 4xx/5xx response, where the request is manually modified and mapped towards a certain response.
See the ["variation" example ](https://github.com/apideck-libraries/portman/tree/main/examples/testsuite-variation-tests)for some more context.

With "fuzzing", Portman automatically alters the request to generate variations, so that you dont have to manually create variations. Typically fuzzing tests, checks how the API behaves if required properties are removed from the request body, ...

See the ["fuzzing" example ](https://github.com/apideck-libraries/portman/tree/main/examples/testsuite-fuzzing-tests)for some more context.

If your OpenAPI has a 401 response defined, you could leverage this so that Portman will create seperate requests just to test the 401 response from your API.

**Comment by thim81** [comment]
@wedi We just pushed a [PR](#320) to bring support for "collectionTestScripts" in Globals, so your request will land in the next release of Portman.

**Comment by wedi** [comment]
Wow. Quick as always. 🚀 

Thanks! ❤️
