### ISSUE TITLE
Error: Too many levels of nesting to fake this schema

### ISSUE THREAD

**Issue by fellnerse** [apideck-libraries/portman#352]
I get an `Error: Too many levels of nesting to fake this schema` and could not find anything about this here in the repo. one of your tests seems to throw this as well: https://github.com/apideck-libraries/portman/search?q=%3CError%3A+Too+many+levels+of+nesting+to+fake+this+schema%3E

Is it possible to specify by hand how many levels of nesting should be allowed? Or is there some other trick to solve this?

thanks in advance!

**Comment by thim81** [comment]
@fellnerse Portman is using the "openapi-to-postman" package behind the scenes.

It seem that the error is caused by the conversion by "[openapi-to-postman]( https://github.com/postmanlabs/openapi-to-postman/blob/develop/OPTIONS.md)" , potentially the `stackLimit`setting is the cause of this error.

We have an example that explains how to specify custom openapi-to-postman settings: https://github.com/apideck-libraries/portman/tree/main/examples/cli-options

Focus on the `"postmanConfigFile": "./examples/cli-options/postman-config.crm.json",`

**Comment by fellnerse** [comment]
Awesome thank you!
here is a minimal working example for future reference:

```json
{
  "optimizeConversion": false,
  "stackLimit": 100,
  "requestParametersResolution": "Example",
  "exampleParametersResolution": "Example"
}
```
