### ISSUE TITLE
Variation overwrites generating incorrect paths

### ISSUE THREAD

**Issue by andmoredev** [apideck-libraries/portman#411]
I am doing overwrites to force a 404 on my endpoints filtered by either openApiOperationId or by openApiOperation (they both fail the same way)

When I generate the postman collection it is overwriting the path variable but it's appending the other path variables to the end of the endpoint url.

The result of having the portman-config.json as attached results in these paths.

![image](https://user-images.githubusercontent.com/33256364/192368784-5033454b-34b4-4b34-bbb2-6e3c725973d2.png)
![image](https://user-images.githubusercontent.com/33256364/192368753-9ae21eef-8675-473a-8c06-0700111141af.png)

You can even see that it appends an inexistentParameter that has an openApiOperation that doesn't match anything in the OpenAPI.

(I changed the filetypes to txt since github didn't let me attach a json file.)
[portman-config.txt](https://github.com/apideck-libraries/portman/files/9649299/portman-config.txt)
[openapi.txt](https://github.com/apideck-libraries/portman/files/9658250/openapi.txt)

**Comment by thim81** [comment]
Hi @andmoredev 

I think, I found the cause.
The variations uses the mostly the same structure, but it can be confusing because of that.
Portman treats each defined `variationTests` is handled as separate variation, all the `test`/`overwrites` are applicable on that specific variation.

**A working Portman config:**
```json
{
  "version": 1,
  "tests": {
    "contractTests": [
      {
        "openApiOperation": "*::/*",
        "statusSuccess": {
          "enabled": true
        }
      },
      {
        "openApiOperation": "*::/*",
        "responseTime": {
          "enabled": false,
          "maxMs": 1500
        }
      },
      {
        "openApiOperation": "*::/*",
        "contentType": {
          "enabled": true
        }
      },
      {
        "openApiOperation": "*::/*",
        "jsonBody": {
          "enabled": true
        }
      },
      {
        "openApiOperation": "*::/*",
        "schemaValidation": {
          "enabled": true
        }
      },
      {
        "openApiOperation": "*::/*",
        "headersPresent": {
          "enabled": true
        }
      }
    ],
    "contentTests": [],
    "extendTests": [],
    "variationTests": [
      {
        "openApiOperation": "*::/*",
        "openApiResponse": "400",
        "variations": [
          {
            "name": "Bad Request",
            "fuzzing": [
              {
                "requestBody": [
                  {
                    "requiredFields": {
                      "enabled": true
                    },
                    "minimumNumberFields": {
                      "enabled": true
                    },
                    "maximumNumberFields": {
                      "enabled": true
                    },
                    "minLengthFields": {
                      "enabled": true
                    },
                    "maxLengthFields": {
                      "enabled": true
                    }
                  }
                ]
              }
            ],
            "tests": {
              "contractTests": [
                {
                  "statusCode": {
                    "enabled": true
                  },
                  "contentType": {
                    "enabled": true
                  },
                  "jsonBody": {
                    "enabled": true
                  },
                  "schemaValidation": {
                    "enabled": true
                  },
                  "headersPresent": {
                    "enabled": true
                  }
                }
              ]
            }
          }
        ]
      },
      {
        "openApiOperation": "GET::/categories/{categoryId}",
        "openApiResponse": "404",
        "variations": [
          {
            "name": "Not Found",
            "tests": {
              "contractTests": [
                {
                  "statusCode": {
                    "enabled": true
                  },
                  "contentType": {
                    "enabled": true
                  },
                  "jsonBody": {
                    "enabled": true
                  },
                  "schemaValidation": {
                    "enabled": true
                  },
                  "headersPresent": {
                    "enabled": true
                  }
                }
              ]
            },
            "overwrites": [
              {
                "overwriteRequestPathVariables": [
                  {
                    "key": "categoryId",
                    "value": "NOTFOUND",
                    "overwrite": true
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "openApiOperation": "PATCH::/products/{productId}",
        "openApiResponse": "404",
        "variations": [
          {
            "name": "Not Found",
            "tests": {
              "contractTests": [
                {
                  "statusCode": {
                    "enabled": true
                  },
                  "contentType": {
                    "enabled": true
                  },
                  "jsonBody": {
                    "enabled": true
                  },
                  "schemaValidation": {
                    "enabled": true
                  },
                  "headersPresent": {
                    "enabled": true
                  }
                }
              ]
            },
            "overwrites": [
              {
                "overwriteRequestPathVariables": [
                  {
                    "key": "productId",
                    "value": "NOTFOUND",
                    "overwrite": true
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "assignVariables": [],
  "overwrites": [],
  "globals": {
    "stripResponseExamples": true,
    "collectionPreRequestScripts": [],
    "keyValueReplacements": {},
    "valueReplacements": {},
    "rawReplacements": [],
    "securityOverwrites": {
      "bearer": {
        "token": ""
      }
    }
  }
} 
```

**Results in Postman:**
<img width="1375" alt="2022-09-27 at 23 06 45@2x" src="https://user-images.githubusercontent.com/952446/192635577-13c834ad-adee-4d6e-9252-2c8d18128941.png">

<img width="1371" alt="2022-09-27 at 23 06 17@2x" src="https://user-images.githubusercontent.com/952446/192635486-15a3b072-cd66-489a-a573-d3817e310f8f.png">

**Some more explanation:**
Your config had a mixture of targetting, where for `variationTests` only the top level is leading and the overwrite targets are ignored.
![2022-09-27 at 23 08 50@2x](https://user-images.githubusercontent.com/952446/192636071-bd580c32-36ba-4313-ac84-3332093b01ad.png)

1. The leading target for your variation
2. The target that is ignored, because of the leading target (1) (unrelated remark you were targeting openApiOperationId while you defined a "path" target)
3. The target that is ignored, because of the leading target (1)
4. The target that is ignored, because of the leading target (1)

**Comment by thim81** [comment]
The variation config can lead to "repetitive" configuration, since Portman allows you to define specific variation expectations/input. To keep the Portman config compact, you can re-use parts by using $ref.

Have a look at the [config-references](https://github.com/apideck-libraries/portman/tree/main/examples/config-references) example for some more details.

**Comment by andmoredev** [comment]
Yes @thim81 !!!
That was it, thankfully it was simply user error.

Thanks for looking into this.
