### ISSUE TITLE
Ordering operations not working with various url path

### ISSUE THREAD

**Issue by laurent-lemke** [apideck-libraries/portman#424]
Hi,

Following the issue raised here: https://github.com/apideck-libraries/portman/issues/423
I found that there is indeed a minimal reproductible case when we have 2 http requests without any folder:
```
GET /users/
POST /users/search
```

Here is the following openAPI yaml corresponding to that:
```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Sample desc
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server

paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/search:
    post:
      summary: search for user
      responses:
        '201': 
          description: A JSON array of searched user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

Given the following portman config yaml:
```json
{
  "version": 1.0,
  "tests": {},
  "globals": {
    "orderOfOperations": ["GET::/users/", "POST::/users/search"]
  }
}
```

I would expect to have the GET operation performed before the POST one.
However, the generated collection has the the POST request before the GET, it is confirmed whenever newman is running it:
```
→ search for user
  POST https://api.toto.com/users/search

→ Returns a list of users.
  GET https://api.toto.com/users 
Collection run completed.
```

Is there any workaround that could exist ? I could put a `tag` but this does not really scale when we have like > 20 requests

**Comment by proDOOMman** [comment]
There is workagound for issue. Just add $ at the end of url in "order of operations":
```json
{
  "version": 1.0,
  "tests": {},
  "globals": {
    "orderOfOperations": ["GET::/users/$", "POST::/users/search$"]
  }
}
```

**Comment by laurent-lemke** [comment]
It doesn't work, POST is still the first request within the generated collection.

**Comment by thim81** [comment]
hi @laurent-lemke & @proDOOMman ,

Thanks for reporting this. We are aware that ordering has it quirks, also because folders have an impact on the structuring of the Postman collection.

I'll have a look if there is a fix or work-a-round. We are also exploring the "Postman flow" capability to see if this might be a better solution than ordering.

**Comment by thim81** [comment]
hi @laurent-lemke,

Looking at the provided YAML

```yaml
paths:
  /users:
    get:
      summary: Returns a list of users.
  /users/search:
    post:
      summary: search for user
```

Without any Portman ordering change, results in this order:
![image](https://user-images.githubusercontent.com/952446/200176200-df6f501d-0c07-4416-a12d-8b75fa760ff3.png)

Your ordering, which is the same order as the OpenApi order BUT notice the `GET::/users/` while the OpenApi doc has `/users`

```json
{
  "version": 1,
  "globals": {
    "stripResponseExamples": true,
    "orderOfOperations": [
      "GET::/users/",
      "POST::/users/search"
    ]
  }
}
```

Results in:
![image](https://user-images.githubusercontent.com/952446/200176332-6f6e00bf-2030-4320-b973-e158b7233443.png)

Using the ordering with `GET::/users` (without  ending `/`)

```json
{
  "version": 1,
  "globals": {
    "stripResponseExamples": true,
    "orderOfOperations": [
      "GET::/users",
      "POST::/users/search"
    ]
  }
}
```

Results in:
![image](https://user-images.githubusercontent.com/952446/200176450-3949dd93-ab60-407b-9092-8a95ba4910b7.png)

The reason is that Portman uses strict matching for the `orderOfOperations` items.

![image](https://user-images.githubusercontent.com/952446/200176539-62a06047-937a-4824-8ce2-c81ec4ebff57.png)

In your example, Portman matched only the `POST::/users/search` which it sorted first and kept the other items as they were defined. 

Our advice is to be as precise as possible when listing the order of operations, otherwise Portman ignores the item while re-ordering.

**Comment by thim81** [comment]
@laurent-lemke If the above explanation helped you solve your issue, could you please the item?
Otherwise we will auto-close it after 7 days?

**Comment by laurent-lemke** [comment]
Gosh yes it totally did, thanks for helping me to notice that !
